config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles   #, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get "signup", to: "users#new"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: {minimum: 3, maximum: 30}
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]
  before_action :set_category, only: [:show, :edit, :update] 

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category Added Successfully"
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice]  = "Category Updated Successfully !!!"
      redirect_to @category
    else
      render "edit"
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admin can add or update a category!!!"
      redirect_to categories_path
    end
  end

end

app/views/categories/_category.html.erb
<div class="container">
<% @categories.each do |category| %>
  <div class="row justify-content-md-center">
    <div class="col-4 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-body">
          <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
          <p><small><%= pluralize(category.articles.count, "article")%></small><p>
          <%= link_to "View Category", category, class: "btn btn-outline-success" %>
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Edit Category", edit_category_path(category), class: "btn btn-outline-info" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
          edited <%= time_ago_in_words(category.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/categories/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
    <%= render 'shared/errors', obj: @category%>
      <%= form_with(model: @category, class: "shadow p-3 mb-3 background rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, "Category Name", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter Category Name" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit(@category.new_record? ? "Create Category" : "Update Category", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit Category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">All Categories</h1>
<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>
<%= render 'category'%>
<div class="flickr_pagination mb-4">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Add Category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name%></h1>
<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
  <%= link_to 'Edit Category', edit_category_path(@category), class:"btn btn-outline-info" %>
  </div>
<% end %>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article'%>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>